name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for making NewPipe better by suggesting a feature. :hug:
        
        Your ideas are highly welcome! It's a tool for you, the users, after all.
        
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I made sure that there are *no existing issues*, neither [open](https://github.com/TeamNewPipe/NewPipe/issues) nor [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed), which I could contribute my information to."
          required: true
        - label: "This is a request for NewPipe itself. Requests for any new service need to be suggested at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues)."
          required: true
        - label: "I am going to take the time to to fill in all the required details. I know that the feature request will be dismissed otherwise."
          required: true
        - label: "This issue contains only one feature request. I will open one issue for every feature I want to request."
          required: true
        - label: "I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md)."
          required: true


  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: |
        Explain how you want the app's look or behavior to change to suit your needs.
    validations:
      required: true

  - type: textarea
    id: why-is-the-feature-requested
    attributes:
      label: Why do you want this feature?
      description: |
        Describe any problem or limitation you come across while using the app which would be solved by this feature.
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any other information you'd like to include, for instance, sketches, mockups, etc.
