name: Question
description: Ask about anything NewPipe-related
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Note that you can also ask questions on our [IRC channel](https://web.libera.chat/#newpipe).

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I made sure that there are *no existing issues*, neither [open](https://github.com/TeamNewPipe/NewPipe/issues) nor [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed), which I could contribute my information to."
          required: true
        - label: "I am going to take the time to to fill in all the required details. I know that the question will be dismissed otherwise."
          required: true
        - label: "I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md)."
          required: true

  - type: textarea
    id: what-is-the-question
    attributes:
      label: What's your question(s)?
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Any other information you'd like to include, for instance, sketches, mockups, etc.
